// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { apiFetch } from '@/api/apiClient';
import { createSafeStorage } from '@/utils/safeStorage';
import { readUnexpiredCachedSession } from '@/lib/auth/authBootstrap';
import { getSupabaseRuntimeConfig, type SupabaseRuntimeEnv } from '@/config/supabaseRuntime';

const runtimeConfig = getSupabaseRuntimeConfig(import.meta.env as unknown as SupabaseRuntimeEnv);
export const hasSupabaseConfig = runtimeConfig.available;

// Keep module evaluation safe when a local desktop build has not been given
// deployment configuration. App.tsx renders a setup screen in this state, and
// this inert client prevents unrelated imports from turning that state into a
// blank renderer before React can mount.
const SUPABASE_URL = runtimeConfig.available
  ? runtimeConfig.url
  : "https://missing-supabase.invalid";
const SUPABASE_KEY = runtimeConfig.available ? runtimeConfig.key : "missing-supabase-config";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabaseUrl = SUPABASE_URL;
const resolvedKey = SUPABASE_KEY;
const authStorage = createSafeStorage();
export const supabaseAuthStorageKey = `sb-${new URL(supabaseUrl).hostname.split('.')[0]}-auth-token`;

/** Bounded bootstrap fallback; the auth client remains refresh authority. */
export const readCachedSessionForBootstrap = () =>
  readUnexpiredCachedSession(authStorage, supabaseAuthStorageKey);

export const supabase = createClient<Database>(supabaseUrl, resolvedKey, {
  auth: {
    storage: authStorage,
    storageKey: supabaseAuthStorageKey,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: apiFetch,
  },
});
